import { LocalModelOption, ModelProvider } from '../types/chat';

export const DEFAULT_LOCAL_MODELS: LocalModelOption[] = [
  // WebGPU & In-Browser Models
  {
    id: 'smollm2-360m-instruct',
    name: 'SmolLM2 360M (Browser WebGPU / Ultra-Fast)',
    provider: 'webgpu',
    size: '360M params',
    parameters: '0.36B',
    recommendedFor: 'Mobile devices, laptops, instant in-browser private inference',
    contextWindow: 4096,
    isRecommended: true,
  },
  {
    id: 'qwen2.5-0.5b-instruct',
    name: 'Qwen 2.5 0.5B (Browser WebGPU / Multilingual)',
    provider: 'webgpu',
    size: '500M params',
    parameters: '0.5B',
    recommendedFor: 'General chat, fast reasoning, multi-language support',
    contextWindow: 8192,
    isRecommended: true,
  },
  {
    id: 'llama-3.2-1b-instruct',
    name: 'Llama 3.2 1B (Browser WebGPU / Meta)',
    provider: 'webgpu',
    size: '1.2B params',
    parameters: '1.2B',
    recommendedFor: 'High precision text, summary, extraction',
    contextWindow: 8192,
  },
  // Ollama Local Models
  {
    id: 'llama3.2:latest',
    name: 'Llama 3.2 (Ollama / 3B)',
    provider: 'ollama',
    size: '2.0 GB',
    parameters: '3.2B',
    recommendedFor: 'Best balanced local model for coding and daily tasks',
    contextWindow: 128000,
    isRecommended: true,
  },
  {
    id: 'deepseek-r1:8b',
    name: 'DeepSeek R1 Distill (Ollama / 8B Reasoning)',
    provider: 'ollama',
    size: '4.9 GB',
    parameters: '8B',
    recommendedFor: 'Complex math, coding, scientific reasoning with thinking chains',
    contextWindow: 64000,
    isRecommended: true,
  },
  {
    id: 'qwen2.5-coder:7b',
    name: 'Qwen 2.5 Coder (Ollama / 7B)',
    provider: 'ollama',
    size: '4.7 GB',
    parameters: '7B',
    recommendedFor: 'Expert programming, debugging, refactoring, algorithms',
    contextWindow: 32768,
  },
  {
    id: 'mistral:latest',
    name: 'Mistral 7B Instruct (Ollama)',
    provider: 'ollama',
    size: '4.1 GB',
    parameters: '7B',
    recommendedFor: 'Fast reasoning, storytelling, markdown formatting',
    contextWindow: 32768,
  },
  {
    id: 'phi4:latest',
    name: 'Phi-4 14B (Ollama / Microsoft)',
    provider: 'ollama',
    size: '9.1 GB',
    parameters: '14B',
    recommendedFor: 'State of the art reasoning and STEM comprehension',
    contextWindow: 16384,
  },
  // LM Studio / LocalAI Models
  {
    id: 'local-model',
    name: 'Active Loaded Model (LM Studio)',
    provider: 'lmstudio',
    size: 'Varies',
    parameters: 'Varies',
    recommendedFor: 'Connects directly to whichever GGUF model is loaded in LM Studio',
    contextWindow: 8192,
    isRecommended: true,
  },
  // Zero-Config In-Browser Engine
  {
    id: 'aether-neural-v1',
    name: 'Aether Local Client Engine (Zero Setup / Offline)',
    provider: 'local_engine',
    size: 'Embedded',
    parameters: 'Client-side',
    recommendedFor: 'Runs everywhere (GitHub Pages, mobile, Safari) with zero setup',
    contextWindow: 8192,
    isRecommended: true,
  },
];

export const PRESET_PROMPTS = [
  {
    id: 'general-assistant',
    title: 'Insightful Local AI',
    category: 'General',
    systemPrompt: 'You are AetherLocal, an exceptionally helpful, polite, and articulate local AI assistant. You answer clearly, provide structured explanations, and respect total privacy.',
    initialUserMessage: 'Hello! What can you help me with today?',
  },
  {
    id: 'senior-dev',
    title: 'Senior Software Engineer',
    category: 'Coding',
    systemPrompt: 'You are a staff software engineer with deep mastery of TypeScript, Python, Rust, algorithms, and system design. Write clean, production-ready code with concise explanations and error handling.',
    initialUserMessage: 'Can you help me design an efficient caching layer in TypeScript?',
  },
  {
    id: 'deep-reasoner',
    title: 'Deep Thinking & Math',
    category: 'Reasoning',
    systemPrompt: 'You are an advanced analytical reasoning model. When answering complex problems, first think through the problem step-by-step inside <think> tags, breaking down logic, assumptions, edge cases, and verifying mathematical rigor before delivering the final answer.',
    initialUserMessage: 'Prove why the square root of 2 is irrational, explaining every step.',
  },
  {
    id: 'creative-writer',
    title: 'Worldbuilder & Storyteller',
    category: 'Creative',
    systemPrompt: 'You are a master creative writer, novelist, and worldbuilder. You craft immersive prose with vivid sensory details, compelling dialogue, and memorable characters.',
    initialUserMessage: 'Write a gripping opening scene set in an antique observatory powered by clockwork stars.',
  },
  {
    id: 'security-privacy',
    title: 'Privacy & Security Auditor',
    category: 'Security',
    systemPrompt: 'You are an ethical security architect specializing in privacy engineering, zero-trust paradigms, local computing, and threat modeling.',
    initialUserMessage: 'How does running local LLMs compare to cloud APIs in terms of threat modeling and data leakage?',
  },
];
